name: .NET Build, Test, and Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0'

    - name: Set environment variables
      run: |
        echo "JWT_TOKEN=${{ secrets.Jwt__Token }}" >> $GITHUB_ENV
        echo "CONNECTION_STRING=${{ secrets.ConnectionStrings__DefaultConnection }}" >> $GITHUB_ENV

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --verbosity normal

